services:
  db:
    image: postgres:12
    hostname: db.example.com
    environment:
      - POSTGRES_USER=foreman
      - POSTGRES_PASSWORD=foreman
      - POSTGRES_DB=foreman
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432'
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U foreman"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - db:/var/lib/postgresql/data

  app: &app_base
    image: quay.io/foreman/foreman:develop
    command: bundle exec bin/rails server -b 0.0.0.0
    working_dir: /home/foreman
    environment:
      - DATABASE_URL=postgres://foreman:foreman@db/foreman?pool=5
      - RAILS_MAX_THREADS=5
      - RAILS_ENV=production
      - BUNDLE_WITHOUT=test:development:openid:libvirt:journald:facter:console:assets
      - FOREMAN_FQDN=foreman.example.com
      - FOREMAN_DOMAIN=example.com
      - FOREMAN_RAILS_CACHE_STORE_TYPE=redis
      - FOREMAN_RAILS_CACHE_STORE_URLS=redis://redis-cache:6379/0
      - DYNFLOW_REDIS_URL=redis://redis-tasks:6379/0
      - REDIS_PROVIDER=DYNFLOW_REDIS_URL
    hostname: foreman.example.com
    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_started
      redis-tasks:
        condition: service_started
    ports:
      - "${MY_DOCKER_IP:-127.0.0.1}:3000:3000"
      - "${MY_DOCKER_IP:-127.0.0.1}:5910-5930:5910-5930"
    restart: always
    volumes:
      - ./app:/home/foreman/app
      - ./db/migrate:/home/foreman/db/migrate
      - ./lib:/home/foreman/lib
      - ./extras:/home/foreman/extras

  orchestrator:
    <<: *app_base
    command: bundle exec sidekiq -r ./extras/dynflow-sidekiq.rb -c 1 -q dynflow_orchestrator
    hostname: orchestrator.example.com
    ports: []

  worker:
    <<: *app_base
    command: bundle exec sidekiq -r ./extras/dynflow-sidekiq.rb -c 15 -q default,1 -q remote_execution,1
    hostname: worker.example.com
    ports: []

  redis-cache:
    image: redis

  redis-tasks:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - redis-persistent:/data

volumes:
  db:
  redis-persistent:
